-- Auto generated by phpMyAdmin

CREATE TABLE `device` (
  `id` int(11) NOT NULL,
  `token` varchar(20) COLLATE utf8_bin NOT NULL,
  `description` varchar(50) COLLATE utf8_bin NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

CREATE TABLE `measure` (
  `id` int(11) NOT NULL,
  `device` int(11) NOT NULL,
  `value` decimal(25,7) NOT NULL,
  `type` int(11) NOT NULL,
  `time_reported` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

CREATE TABLE `measure_type` (
  `id` int(11) NOT NULL,
  `name` varchar(15) COLLATE utf8_bin NOT NULL,
  `unit` varchar(5) COLLATE utf8_bin NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

CREATE TABLE `user` (
  `id` int(11) NOT NULL,
  `name` varchar(50) COLLATE utf8_bin NOT NULL,
  `password` varchar(32) COLLATE utf8_bin NOT NULL COMMENT 'sizeof(sha256)'
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

ALTER TABLE `device`
  ADD PRIMARY KEY (`id`);

ALTER TABLE `measure`
  ADD PRIMARY KEY (`id`),
  ADD KEY `FK_measure_to_type` (`type`),
  ADD KEY `FK_measure_to_device` (`device`);

ALTER TABLE `measure_type`
  ADD PRIMARY KEY (`id`);

ALTER TABLE `user`
  ADD PRIMARY KEY (`id`);

ALTER TABLE `device`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;

ALTER TABLE `measure`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;

ALTER TABLE `measure_type`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;

ALTER TABLE `user`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;

ALTER TABLE `measure`
  ADD CONSTRAINT `FK_measure_to_device` FOREIGN KEY (`device`) REFERENCES `device` (`id`),
  ADD CONSTRAINT `FK_measure_to_type` FOREIGN KEY (`type`) REFERENCES `measure_type` (`id`);
COMMIT;

